-- Baseline schema migration.
--
-- Generated by: booting the application with the PRE-Flyway
-- `spring.jpa.hibernate.ddl-auto=update` configuration against an empty PostgreSQL 17
-- database, then `pg_dump --schema-only`. This captures, byte-for-byte, the schema
-- Hibernate itself created from the current JPA entities — it is not hand-authored.
-- Cleaned of pg_dump noise (SET session config, \restrict/\unrestrict guards, and
-- `ALTER TABLE ... OWNER TO` ownership statements), which are irrelevant to any
-- environment this application runs in.
--
-- This is version 1 of the schema history — do not edit this file once it has
-- shipped to any environment; add a new versioned migration instead.

--
-- Name: addresses; Type: TABLE; Schema: public
--

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    city character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_default boolean NOT NULL,
    label character varying(100),
    notes character varying(500),
    postal_code character varying(20),
    street character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL
);

--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: cart_items; Type: TABLE; Schema: public
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    cart_id bigint NOT NULL,
    menu_item_id bigint NOT NULL,
    CONSTRAINT cart_items_quantity_check CHECK (((quantity > 0) AND (quantity <= 50)))
);

--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: carts; Type: TABLE; Schema: public
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint
);

--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: categories; Type: TABLE; Schema: public
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    icon character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: coupon_usages; Type: TABLE; Schema: public
--

CREATE TABLE public.coupon_usages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    coupon_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    order_id bigint NOT NULL
);

--
-- Name: coupon_usages_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.coupon_usages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupon_usages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: coupons; Type: TABLE; Schema: public
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    discount_type character varying(20) NOT NULL,
    discount_value numeric(10,2) NOT NULL,
    ends_at timestamp(6) without time zone,
    max_discount_amount numeric(10,2),
    min_order_amount numeric(10,2),
    starts_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    usage_limit integer,
    restaurant_id bigint,
    CONSTRAINT coupons_check CHECK (((discount_value > (0)::numeric) AND (((discount_type)::text <> 'PERCENTAGE'::text) OR (discount_value <= (100)::numeric)) AND ((min_order_amount IS NULL) OR (min_order_amount >= (0)::numeric)) AND ((max_discount_amount IS NULL) OR (max_discount_amount > (0)::numeric)) AND ((usage_limit IS NULL) OR (usage_limit > 0)) AND ((starts_at IS NULL) OR (ends_at IS NULL) OR (ends_at > starts_at)))),
    CONSTRAINT coupons_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying])::text[])))
);

--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: favorites; Type: TABLE; Schema: public
--

CREATE TABLE public.favorites (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint NOT NULL
);

--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: menu_categories; Type: TABLE; Schema: public
--

CREATE TABLE public.menu_categories (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    restaurant_id bigint NOT NULL
);

--
-- Name: menu_categories_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.menu_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: menu_items; Type: TABLE; Schema: public
--

CREATE TABLE public.menu_items (
    id bigint NOT NULL,
    available boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(1000),
    display_order integer NOT NULL,
    image_url character varying(500),
    name character varying(150) NOT NULL,
    price numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    category_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT menu_items_price_check CHECK ((price >= (0)::numeric))
);

--
-- Name: menu_items_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.menu_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: order_items; Type: TABLE; Schema: public
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    image_url character varying(500),
    line_total numeric(10,2) NOT NULL,
    menu_item_id bigint NOT NULL,
    name character varying(150) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT order_items_check CHECK (((quantity > 0) AND (unit_price >= (0)::numeric) AND (line_total >= (0)::numeric)))
);

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: orders; Type: TABLE; Schema: public
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    coupon_code character varying(30),
    created_at timestamp(6) without time zone NOT NULL,
    delivery_city character varying(100) NOT NULL,
    delivery_fee numeric(10,2) NOT NULL,
    delivery_label character varying(100),
    delivery_notes character varying(500),
    delivery_postal_code character varying(20),
    delivery_street character varying(255) NOT NULL,
    discount numeric(10,2) NOT NULL,
    order_number character varying(30) NOT NULL,
    payment_method character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT orders_check CHECK (((subtotal >= (0)::numeric) AND (delivery_fee >= (0)::numeric) AND (discount >= (0)::numeric) AND (total >= (0)::numeric))),
    CONSTRAINT orders_payment_method_check CHECK (((payment_method)::text = 'CASH_ON_DELIVERY'::text)),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'CONFIRMED'::character varying, 'PREPARING'::character varying, 'ON_THE_WAY'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: platform_settings; Type: TABLE; Schema: public
--

CREATE TABLE public.platform_settings (
    id bigint NOT NULL,
    allow_restaurant_registration boolean NOT NULL,
    commission_percentage numeric(5,2) NOT NULL,
    default_delivery_fee numeric(10,2) NOT NULL,
    maintenance_mode boolean NOT NULL,
    support_email character varying(150),
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT platform_settings_check CHECK (((commission_percentage >= (0)::numeric) AND (commission_percentage <= (100)::numeric) AND (default_delivery_fee >= (0)::numeric)))
);

--
-- Name: restaurant_categories; Type: TABLE; Schema: public
--

CREATE TABLE public.restaurant_categories (
    restaurant_id bigint NOT NULL,
    category_id bigint NOT NULL
);

--
-- Name: restaurants; Type: TABLE; Schema: public
--

CREATE TABLE public.restaurants (
    id bigint NOT NULL,
    approval_status character varying(20) NOT NULL,
    close_time time(0) without time zone,
    cover_image_url character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    cuisine character varying(150) NOT NULL,
    delivery_fee numeric(10,2) NOT NULL,
    estimated_delivery_max_minutes integer NOT NULL,
    estimated_delivery_min_minutes integer NOT NULL,
    logo_url character varying(500),
    minimum_order numeric(10,2) NOT NULL,
    name character varying(150) NOT NULL,
    is_open_for_orders boolean NOT NULL,
    open_time time(0) without time zone,
    rating_average numeric(3,2) NOT NULL,
    review_count integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT restaurants_approval_status_check CHECK (((approval_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'SUSPENDED'::character varying])::text[]))),
    CONSTRAINT restaurants_check CHECK (((estimated_delivery_max_minutes >= estimated_delivery_min_minutes) AND (delivery_fee >= (0)::numeric) AND (minimum_order >= (0)::numeric) AND (rating_average >= (0)::numeric) AND (rating_average <= (5)::numeric) AND (review_count >= 0) AND ((open_time IS NULL) OR (close_time IS NULL) OR (close_time > open_time))))
);

--
-- Name: restaurants_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.restaurants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'OWNER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Primary key / unique constraints
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT coupon_usages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.menu_categories
    ADD CONSTRAINT menu_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT menu_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.platform_settings
    ADD CONSTRAINT platform_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.restaurant_categories
    ADD CONSTRAINT restaurant_categories_pkey PRIMARY KEY (restaurant_id, category_id);

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk88sv4i13lo80s74ox7rsb5a2c UNIQUE (customer_id);

ALTER TABLE ONLY public.menu_categories
    ADD CONSTRAINT ukb0cyd69e9rptrft1d674hlhrn UNIQUE (restaurant_id, name);

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukeplt0kkm9yf2of2lnx6c1oy9b UNIQUE (code);

ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT ukgsn0fhgy76p51v5h30akhc063 UNIQUE (order_id);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT ukgsowgy310wsxbciw7r1xlgn5a UNIQUE (cart_id, menu_item_id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number);

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT ukqfosjx8hjdmn2trfs9j4t2eoe UNIQUE (customer_id, restaurant_id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Foreign key constraints
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fk1wwmot9772p901aismub7pd5c FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk2m9qulf12xm537bku3jnrrbup FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);

ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT fk3mvslb8gc0ac6501mfmvifgva FOREIGN KEY (coupon_id) REFERENCES public.coupons(id);

ALTER TABLE ONLY public.restaurant_categories
    ADD CONSTRAINT fk4kg1d5bcfdt8fn2qh16ptrnfm FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT fk4pc1grgsms7nqm2i6oig37pro FOREIGN KEY (category_id) REFERENCES public.menu_categories(id);

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fk56bvektuw7xi7dgfqyd9kcdh2 FOREIGN KEY (customer_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk5ishcgpt4w7kbpwmh9e0mio8s FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fk99i1rh5nm7r3f1b3wdcuq5h57 FOREIGN KEY (customer_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT fkbeu0hws89mcmixcll2ggn4udw FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);

ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT fkbup0uymjwu9gtnrwwsqm16c2 FOREIGN KEY (customer_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT fkhaqtoboitpl0n541y0sc753my FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);

ALTER TABLE ONLY public.restaurant_categories
    ADD CONSTRAINT fkiq9qlrhc1dciym7ai5m4bva27 FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);

ALTER TABLE ONLY public.menu_categories
    ADD CONSTRAINT fkkx2gof9mxsye30ju5et6a865p FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fkntby5i9ckfbhd9spu3x1ef5oo FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fkq0roe5usabjpwwflsnuscjerx FOREIGN KEY (customer_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT fks9yuckyrsqcsgmjsus1unapt4 FOREIGN KEY (order_id) REFERENCES public.orders(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fksjfs85qf6vmcurlx43cnc16gy FOREIGN KEY (customer_id) REFERENCES public.users(id);
