-- V5 — Reviews & ratings domain (BACKEND-005).
--
-- Creates the `reviews` table that backs:
--   * GET  /api/v1/reviews                      — homepage testimonials strip
--   * POST /api/v1/orders/{orderId}/reviews     — a customer's one review per delivered order
-- plus the indexes the rating-aggregation recompute
-- (restaurants.rating_average / restaurants.review_count) reads on every review create.
--
-- `spring.jpa.hibernate.ddl-auto=validate` will NOT create this table — it ships here or the
-- application fails to boot with a SchemaManagementException against
-- com.food.foodapp.review.entity.Review. Column names / types / nullability below mirror exactly
-- what Hibernate generates for that entity (bigint identity id, timestamp(6) audit columns,
-- varchar(2000) comment), so schema validation passes.
--
-- Safe against a database that already holds rows: `reviews` is a brand-new relation that no
-- prior schema ever created (V1 baseline has no reviews table, and the pre-Flyway
-- ddl-auto=update era never had a Review entity), so a plain CREATE TABLE cannot collide with
-- anything. No backfill is needed — the table starts empty and every existing restaurant row
-- already carries rating_average = 0.00 / review_count = 0 from V1.

CREATE TABLE public.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    rating integer NOT NULL,
    comment character varying(2000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id),
    CONSTRAINT reviews_rating_check CHECK ((rating >= 1) AND (rating <= 5)),
    CONSTRAINT uk_reviews_order_id UNIQUE (order_id),
    CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES public.orders(id),
    CONSTRAINT fk_reviews_restaurant FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES public.users(id)
);

CREATE INDEX idx_reviews_restaurant ON public.reviews (restaurant_id);
CREATE INDEX idx_reviews_restaurant_rating ON public.reviews (restaurant_id, rating);
