-- V7 — Password reset flow (BACKEND-009).
--
-- Creates the `password_reset_tokens` table that backs:
--   * POST /api/v1/auth/forgot-password  — issue a single-use reset token and email its link
--   * POST /api/v1/auth/reset-password   — consume the token and set a new password
--
-- `spring.jpa.hibernate.ddl-auto=validate` will NOT create this table — it ships here or the
-- application fails to boot with a SchemaManagementException against
-- com.food.foodapp.auth.entity.PasswordResetToken. Column names / types / nullability below
-- mirror exactly what Hibernate generates for that entity (bigint identity id, timestamp(6)
-- audit columns, varchar(64) token_hash), so schema validation passes.
--
-- Only the SHA-256 hex digest of a token is ever stored (`token_hash`, 64 hex chars) — never the
-- raw token that is emailed to the user. A read of this table cannot be replayed against the
-- reset endpoint. `used_at` is NULL until the token is consumed; a token is valid only while
-- `used_at IS NULL AND expires_at > now()`.
--
-- Safe against a database that already holds rows: `password_reset_tokens` is a brand-new
-- relation that no prior schema ever created (V1 baseline has no such table, and the pre-Flyway
-- ddl-auto=update era never had a PasswordResetToken entity), so a plain CREATE TABLE cannot
-- collide with anything. No backfill is needed — the table starts empty.

CREATE TABLE public.password_reset_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    used_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE INDEX idx_password_reset_tokens_hash ON public.password_reset_tokens (token_hash);
